version: "2"

services:
  jack:
    build:
      context: .
    hostname: jack
    domainname: jack.jackcore.org
    restart: always
    ports:
      - "7777:7777"
    volumes:
      - "./coindata:/var/lib/coindata"
    environment:
      MINING: false
      STAKING: false
      MASTERNODE: false
